### ISSUE TITLE
New data for cri-containerd.

### ISSUE THREAD

**Issue by Random-Liu** [kunalkushwaha/ctr-powertest#3]
We made some performance optimization recently.

Can you try cri-containerd HEAD and update the data?

@kunalkushwaha

**Comment by kunalkushwaha** [comment]
Hi @Random-Liu , Sorry for delay response.

I ran an updated test result for ``cri-containerd`` and ``containerd``. 
_I couldn't get result for cri-o yet, due to some issue. Will do it later, once it is fixed._

__Observation__: Noticeable improvement in cri-ctrd ``create operation``

#### cri-containerd
```
$ sudo ./ctr-powertest -p cri -r cri-containerd profile 
[sudo] password for kunal:        
INFO[0000] Running tests on &VersionResponse{Version:0.1.0,RuntimeName:cri-containerd,RuntimeVersion:1.0.0-beta.1-90-g2fa185c-dirty,RuntimeApiVersion:0.0.0,} 
 

Container Profile data

        Create  Start   Stop    Delete
Min     0.61s   0.14s   0.10s   0.34s
Avg     0.78s   0.17s   0.12s   0.38s
Max     4.50s   0.36s   0.14s   0.49s
Total   39.03s  8.59s   5.84s   19.23s
```


#### containerd
```
$ sudo ./ctr-powertest profile                 
INFO[0000] Running tests on containerd v1.0.0-161-g91d93e2.m 

Container Profile data

        Create  Start   Stop    Delete
Min     0.15s   0.03s   0.06s   0.06s
Avg     0.19s   0.04s   0.08s   0.08s
Max     0.27s   0.04s   0.08s   0.20s
Total   9.39s   1.90s   3.84s   4.11s
```

**Comment by kunalkushwaha** [comment]
###   1.0.0-beta.1 vs 1.0.0-alpha.1 
![cri-improvement](https://user-images.githubusercontent.com/2758433/35903235-a2886e86-0c21-11e8-984b-aa458ab273ac.jpg)

**Comment by Random-Liu** [comment]
@kunalkushwaha Thanks a lot for the update! :) We made some CNI optimization, which reduces the startup latency as expected.

**Comment by kunalkushwaha** [comment]
Updated with cri-o numbers too.

![container runtime comparision - update-feb](https://user-images.githubusercontent.com/2758433/35955901-b00cb8d2-0cd5-11e8-9aeb-0657f8c315f3.png)

**Comment by Random-Liu** [comment]
Close this one. @kunalkushwaha Thanks for collecting new data! :)
